"""remove ver number of the token db

Revision ID: 0b7218384886
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 15:24:47.009620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b7218384886'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refreshtoken', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refreshtoken', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('refreshtoken', 'token_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('token_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('refreshtoken', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refreshtoken', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
