"""make short code url nullable

Revision ID: 33d24c5a1a34
Revises: 642c9e200d87
Create Date: 2026-06-03 17:32:16.426687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33d24c5a1a34'
down_revision: Union[str, Sequence[str], None] = '642c9e200d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urlmap', 'short_url_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urlmap', 'short_url_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
