"""create users table

Revision ID: b337a7fcc015
Revises: 33d24c5a1a34
Create Date: 2026-06-15 11:58:40.566148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b337a7fcc015'
down_revision: Union[str, Sequence[str], None] = '33d24c5a1a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urlmap', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'urlmap', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urlmap', type_='foreignkey')
    op.drop_column('urlmap', 'owner_id')
    # ### end Alembic commands ###
